services:

  postgres:
    image: postgres
    container_name: postgres-single-service
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres-single-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-single-service
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.ca
      PGADMIN_DEFAULT_PASSWORD: password



# ---- POSTGRES_USER: admin         (not essential) default POSTGRES_USER: postgres
# ---- POSTGRES_PASSWORD: password  (not essential) default POSTGRES_PASSWORD: none