#version: '4.0'

services:

  mongodb:
    image: mongo:latest
    container_name: initdb-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - initdb-network

  mongo-express:
    image: mongo-express
    container_name: initdb-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - initdb-network


networks:
  initdb-network:
    driver: bridge


# ---- this file initializes the MongoDB service --> preloaded data --> uses mongo-init.js
# ---- keep for isolated DB initialization scripts/debugging/testing